Task 60 game main features
5dev-team/BattleCity pull request #11
Opened 2022-12-02 22:12 UTC by thechertan

### Какую задачу решаем:
1.Загрузка уровня
2.Реализована подгрузка текстур из спрайта(ВАЖНО, не всех, а только тех текстур, которые нужны для первого уровня!)
3.Реализована анимация движения танка в движении(извините за тавтологию, но это так)
4.Передвижения танка по всему уровню
5.Столкновения танка с препятствиями(танк их видит)
6.Добавлена коллизия(работает так, если не доезжаете до условного поворота танк сам подстраивается под тот самый поворот(танк 32 на 32 не доехали 8px и меньше - танк сам повернет), есть нюансы, если вы чуть дальше проедете, то танк упрется в блок(сетку), если сравнивать с оригиналом такого быть не должно.
7. Реализована стрельба.
8. Реализована анимация взрыва снаряда.
9. Карты можно собирать через код(главное добавить спрайт тех текстур, которые вы хотите добавить) constants/levels key => stage

### Скриншоты/видяшка (если есть)
![205396913-c42704af-ccca-4c7e-8103-280c87a45b9d](https://user-images.githubusercontent.com/84693047/205398854-0dccb318-8ab4-4cc9-82ff-d99ee4511b59.png)

### TODO (если есть)
Реализация ботов => простых, нажимают рандомные клавиши рандомное время - currentFrame переменная которая считает время между перерисовками кадров, она уже в движке(Game) как раз её и можно использовать.
Реализовать повреждение стен, у стен должен быть damage, повреждение стен не должно быть как у оригинальной игры, иначе мы закопаемся, если будет время то можно и сделать.
Так как снаряд, а точнее стена уже понимает куда попал снаряд, то у стены нужно отнимать или прибавлять damage и заменять sprite, а также пересовывать Stage(мир) чтобы танк мог заехать где стены уже нет, все делать как в игре не обязательно!
Реализация damage Base(базы) при условном попадании в неё уровень заканчивается(Game Over)
5.Реализация damage Танка, в принципе так же как и у базы - 1 попадание Game Over

2022-12-03 10:59 UTC, EzhikTT commented on packages/client/src/game/classesGame/Base/Base.ts
> +import GameObject from '../GameObject/GameObject'
Почему здесь не через `@` подключение?

2022-12-03 11:01 UTC, EzhikTT requested changes
В закрытом [ПРе](https://github.com/5dev-team/BattleCity/pull/8) замечания такие же, как и здесь. Дублирую:
Общие замечание, которые нужно исправить или пояснить:
1) почему у всех классов свойства и методы - публичные?
2) на публичные свойства используются геттеры, в чем смысл?
3) почему есть @ts-ignore? Какие ошибки компилятора на этих строчках?
4) нигде не readonly, хотя, кроме как в конструкторе, не вижу обновления значений

2022-12-03 20:12 UTC, thechertan commented on packages/client/src/game/classesGame/Base/Base.ts
> +import GameObject from '../GameObject/GameObject'
Исправил, не знал что есть алиасы

2022-12-06 15:55 UTC, EzhikTT requested changes
Ок, только один вопрос остался

2022-12-06 15:55 UTC, EzhikTT commented on packages/client/src/game/classesGame/EnemyTank/EnemyTank.ts
> +  public speed: number
Они должны быть публичные? Не нужно ничего проверять через сеттеры?

2022-12-06 21:09 UTC, thechertan commented on packages/client/src/game/classesGame/EnemyTank/EnemyTank.ts
> +  public speed: number
данный метод пока что не используется, просто заложен на будущее и предназначен для ботов, в данный момент его можно удалить

2022-12-06 21:18 UTC, thechertan commented on packages/client/src/game/classesGame/EnemyTank/EnemyTank.ts
> +  public speed: number
а вообще должен быть: protected speed: number
с данным классом еще возиться и возиться, поэтому и оставил всё публичным :)

2022-12-07 20:17 UTC, EzhikTT commented on packages/client/src/game/classesGame/EnemyTank/EnemyTank.ts
> +  public speed: number
Ну ладно -_-

2022-12-07 20:17 UTC, EzhikTT approved these changes
Кроме публичности скорости все ок

2022-12-18 18:06 UTC, sokol-rc approved these changes

2022-12-18 18:06 UTC, sokol-rc commented on packages/client/src/game/classesGame/Game/Game.ts
> +  private stage?: Stage | null
не думаю, что stage может быть undefined

2022-12-18 18:06 UTC, sokol-rc commented on packages/client/src/game/classesGame/Stage/Stage.ts
> +    objectsArr.filter(obj => obj != undefined && 'update' in obj).map(obj => obj as IUpdatable).forEach((object: IUpdatable) => {
Лучше использовать строго сравнение

2022-12-18 18:06 UTC, sokol-rc commented on packages/client/src/game/classesGame/Stage/Stage.ts
> +    objectsArr.filter(obj => obj != undefined && 'update' in obj).map(obj => obj as IUpdatable).forEach((object: IUpdatable) => {
`object: IUpdatable)` лишнее. Для читаемости добавлено?

2022-12-19 14:15 UTC, thechertan commented on packages/client/src/game/classesGame/Game/Game.ts
> +  private stage?: Stage | null
> не думаю, что stage может быть undefined

Да, обязательное поле сделал.

2022-12-19 14:17 UTC, thechertan commented on packages/client/src/game/classesGame/Stage/Stage.ts
> +    objectsArr.filter(obj => obj != undefined && 'update' in obj).map(obj => obj as IUpdatable).forEach((object: IUpdatable) => {
> Лучше использовать строго сравнение

Согласен

2022-12-19 14:18 UTC, thechertan commented on packages/client/src/game/classesGame/Stage/Stage.ts
> +    objectsArr.filter(obj => obj != undefined && 'update' in obj).map(obj => obj as IUpdatable).forEach((object: IUpdatable) => {
> `object: IUpdatable)` лишнее. Для читаемости добавлено?

Да, чтобы понимать что из себя представляет obj

2022-12-19 14:44 UTC, merged