Верстка страницы профиля
5dev-team/BattleCity pull request #12
Opened 2022-12-04 23:53 UTC by sokol-rc

### Какую задачу решаем
URL страницы: `/profile`
Вёрстка страницы профиля. 
Изменение параметров профиля аватар, пароли и другие данные на одной странице.
Поле аватар с Drag’n’Drop.

### Скриншот
View mode:
![изображение](https://user-images.githubusercontent.com/83005607/205523341-8ca03c4f-12d2-4c7e-89de-c57f0e69c39a.png)

Edit mode:
![изображение](https://user-images.githubusercontent.com/83005607/205523421-3e805a81-8f08-468a-89d3-931172b4bbc5.png)

2022-12-05 17:52 UTC, Underwindow requested changes
Хорошая работа! Только нужно пофиксить drag&drop, а в остальном всё супер.

2022-12-05 17:52 UTC, Underwindow commented on packages/client/src/components/UI/nes-file-input/nes-file-input.tsx
> +interface INesInputProps extends InputHTMLAttributes<HTMLInputElement> {
Почему тип пропсов объявлен через интерфейс, а не через `type`?

2022-12-05 17:52 UTC, Underwindow commented on packages/client/src/components/UI/nes-file-input/nes-file-input.tsx
> +          <div>Load avatar</div>
Как вариант можно сообщить пользователю, что изображение можно перетащить. Написать например так: "Choose file / Drag&Drop"

2022-12-05 17:52 UTC, Underwindow commented on .eslintrc.js
> +    'jsx-quotes': ['error', 'prefer-double'],
Почему было добавлено новое правило?

2022-12-05 17:52 UTC, Underwindow commented on packages/client/src/components/UI/nes-file-input/nes-file-input.module.scss
> +  &__input {
Нужно добавить стиль для :disabled. Дело в том, что даже пока не была нажата кнопка edit profile, курсор меняется, когда наводишь мышку на элемент с аватаром.

2022-12-05 17:52 UTC, Underwindow commented on packages/client/src/pages/profile/profile.tsx
> +  const handleDragStart = (e: DragEvent<HTMLInputElement>) => {
Нужно добавить проверку на `mode`. На данный момент можно перетащить файл без нажатия на кнопку edit profile

2022-12-05 18:01 UTC, Underwindow commented on packages/client/src/components/UI/nes-file-input/nes-file-input.tsx
> +          <div>Load avatar</div>
Также можно еще подумать над тем будет ли лучше, если поместить надпись Choose avatar над аватаром? Текущая близость текста кнопки удаления и выбора аватара немного смущает.

2022-12-05 18:10 UTC, sokol-rc commented on packages/client/src/components/UI/nes-file-input/nes-file-input.tsx
> +interface INesInputProps extends InputHTMLAttributes<HTMLInputElement> {
чтобы расширить существующие пропсы инпута, при этом не описывать каждые отдельно

2022-12-05 18:11 UTC, sokol-rc commented on packages/client/src/components/UI/nes-file-input/nes-file-input.tsx
> +          <div>Load avatar</div>
на Drag&Drop намекает рамка пунктирная
Наверно этого не достаточно, всё-таки.

2022-12-05 19:14 UTC, Underwindow requested changes
Нужно учитывать соотношение сторон аватара, например обрезать изображение до квадрата.
![image](https://user-images.githubusercontent.com/35759068/205722438-d82c00e3-8420-41e8-8263-0783da9abfe7.png)
Лучше изменить цвет надписи Drag&Drop с синего на белый. Синий цвет ассоциируется с элементом взаимодействия, хотя это просто текст.
В остальном круто! Баг с drag&drop'ом ушел из хрома.

2022-12-05 19:31 UTC, sokol-rc commented on .eslintrc.js
> +    'jsx-quotes': ['error', 'prefer-double'],
Чтобы в jsx были двойные кавычки, так привычнее

2022-12-05 19:32 UTC, Underwindow approved these changes
Всё здорово!

2022-12-06 15:50 UTC, EzhikTT requested changes

2022-12-06 15:50 UTC, EzhikTT commented on packages/client/src/pages/profile/profile.tsx
> +    console.log({
Лог очень нужен в репозитории?

2022-12-06 15:50 UTC, EzhikTT commented on .eslintrc.js
> +    'jsx-quotes': ['error', 'prefer-double'],
Вкусовщина. Внутри команды согласовано?

2022-12-07 18:03 UTC, sokol-rc commented on packages/client/src/pages/profile/profile.tsx
> +    console.log({
А как можно сообщить следующему разработчику, какие поля передавать в стейт из формы? в 1 модуле учили так

2022-12-07 18:04 UTC, sokol-rc commented on packages/client/src/pages/profile/profile.tsx
> +    console.log({
а комментарии были запрещены ¯\_(ツ)_/¯

2022-12-07 20:18 UTC, EzhikTT commented on packages/client/src/pages/profile/profile.tsx
> +    console.log({
Оки)

2022-12-07 20:18 UTC, EzhikTT approved these changes
Все хорошо

2022-12-07 22:58 UTC, merged