Task 29 screen game over
5dev-team/BattleCity pull request #15
Opened 2022-12-08 17:30 UTC by thechertan

### Какую задачу решаем
1. Сверстать страницу окончания игры

### Скриншоты/видяшка (если есть)
![image](https://user-images.githubusercontent.com/84693047/206522413-806627c6-8d04-4af6-a6dd-2c6bbcb4dd82.png)
![image](https://user-images.githubusercontent.com/84693047/206522490-ee672bb2-fd19-45ab-b7ff-0d1f342da169.png)

### TBD (если есть)

2022-12-09 06:05 UTC, EzhikTT commented on packages/client/src/pages/screen-game-over/screen-game-over.tsx
> +import T0 from '@/assets/tanks/1T.png'
А почему в названиях файлов наоборот?

2022-12-09 06:06 UTC, EzhikTT commented on packages/client/src/pages/screen-game-over/screen-game-over.tsx
> +          <p className={styles['players-stats__arrow']}>🡄</p>
Тут символ поломался?

2022-12-09 06:06 UTC, EzhikTT approved these changes
Норм)

2022-12-10 17:27 UTC, thechertan commented on packages/client/src/pages/screen-game-over/screen-game-over.tsx
> +          <p className={styles['players-stats__arrow']}>🡄</p>
видимо на unix подобных системах этого знака нет, на windows есть, переделаю на svg

2022-12-10 17:31 UTC, thechertan commented on packages/client/src/pages/screen-game-over/screen-game-over.tsx
> +import T0 from '@/assets/tanks/1T.png'
Это важно?

2022-12-12 21:21 UTC, sokol-rc requested changes
Есть несколько замечаний, которые лучше исправить:

- убрать лишние вычисления

2022-12-12 21:21 UTC, sokol-rc commented on packages/client/src/App.tsx
> +import ScreenGameOver from '@/pages/screen-game-over/screen-game-over'
У нас все страницы называются без приставки Screen, почему так сделал?

2022-12-12 21:21 UTC, sokol-rc commented on packages/client/src/App.tsx
> +import ScreenGameOver from '@/pages/screen-game-over/screen-game-over'
У тебя в папке screen-game-over есть `index.ts` где `export default ScreenGameOver`, а в этом пути ты его не используешь

2022-12-12 21:21 UTC, sokol-rc commented on packages/client/src/constants/sprites.ts
> +
Зачем этот файл? нигде не используется

2022-12-12 21:21 UTC, sokol-rc commented on packages/client/src/pages/screen-game-over/screen-game-over.tsx
> +      <li className={`${styles['players-stats__item']} ${props.players === 1 && styles['players-stats__item_one']}`}
`${props.players === 1 && styles['players-stats__item_one']}` лучше поменять на
`${props.players === 1 ? styles['players-stats__item_one'] : ''}`
иначе в класс запишется false если условие не выполнится

2022-12-12 21:21 UTC, sokol-rc commented on packages/client/src/pages/screen-game-over/screen-game-over.module.scss
> +    font-weight: 400;
а для чего тут font-weight? Он ведь такой же у body

2022-12-12 21:21 UTC, sokol-rc commented on packages/client/src/pages/screen-game-over/screen-game-over.module.scss
> +    flex-direction: row;
row initial значение для flex-direction
Отдельно указывать излишне

2022-12-12 21:21 UTC, sokol-rc commented on packages/client/src/pages/screen-game-over/screen-game-over.module.scss
> +    font-weight: 400;
а для чего тут font-weight? Он ведь такой же у body

2022-12-12 21:21 UTC, sokol-rc commented on packages/client/src/pages/screen-game-over/screen-game-over.module.scss
> +    font-weight: 400;
а для чего тут font-weight? Он ведь такой же у body

2022-12-12 21:21 UTC, sokol-rc commented on packages/client/src/pages/screen-game-over/screen-game-over.module.scss
> +  flex-direction: column;
А зачем column если 1 потомок?

2022-12-12 21:21 UTC, sokol-rc commented on packages/client/src/pages/screen-game-over/screen-game-over.tsx
> +    }, { P1: 0, P2: 0 })
Расчет totalScore лучше оставить на стороне бизнес логики. Пусть вью занимается простым отображением.
Во входящем объекте данных просто добавь totalScore для каждого игрока

2022-12-12 21:21 UTC, sokol-rc commented on packages/client/src/pages/screen-game-over/screen-game-over.tsx
> +          <p className={styles['players-stats__pts-count']}>{value.P1 ? (value.P1 * (100 * (index + 1))) : 0}</p>
Вычисления лучше вынести в переменную. А еще лучше получать сразу готовые данные

2022-12-12 21:42 UTC, thechertan commented on packages/client/src/App.tsx
> +import ScreenGameOver from '@/pages/screen-game-over/screen-game-over'
![image](https://user-images.githubusercontent.com/84693047/207160717-b563d9ea-1383-4c5e-8d45-bc10d086de1a.png)

2022-12-12 21:47 UTC, thechertan commented on packages/client/src/pages/screen-game-over/screen-game-over.tsx
> +      <li className={`${styles['players-stats__item']} ${props.players === 1 && styles['players-stats__item_one']}`}
Почему лучше?

2022-12-12 21:53 UTC, thechertan commented on packages/client/src/pages/screen-game-over/screen-game-over.module.scss
> +    font-weight: 400;
Не знаю как но яндекс постоянно учил, что если наследовать стили шрифтов от родителя, то это является плохой практикой. Правда там был БЭМ, тут нет его и как быть не знаю....

2022-12-12 21:55 UTC, thechertan commented on packages/client/src/constants/sprites.ts
> +
![image](https://user-images.githubusercontent.com/84693047/207163410-928e392a-b1ca-432b-b703-440eeae7a02f.png)

2022-12-14 21:37 UTC, thechertan commented on packages/client/src/App.tsx
> +import ScreenGameOver from '@/pages/screen-game-over/screen-game-over'
> У нас все страницы называются без приставки Screen, почему так сделал?

Исправил

2022-12-14 21:38 UTC, thechertan commented on packages/client/src/App.tsx
> +import ScreenGameOver from '@/pages/screen-game-over/screen-game-over'
> У тебя в папке screen-game-over есть `index.ts` где `export default ScreenGameOver`, а в этом пути ты его не используешь

так предложил автокомплит, исправил

2022-12-14 21:41 UTC, thechertan commented on packages/client/src/constants/sprites.ts
> +
> Зачем этот файл? нигде не используется

в начале думал сделать через спрайты, так как сама картинка спрайтов уже есть, но не получилось, удалил.

2022-12-14 21:47 UTC, thechertan commented on packages/client/src/pages/screen-game-over/screen-game-over.tsx
> +      <li className={`${styles['players-stats__item']} ${props.players === 1 && styles['players-stats__item_one']}`}
> `${props.players === 1 && styles['players-stats__item_one']}` лучше поменять на `${props.players === 1 ? styles['players-stats__item_one'] : ''}` иначе в класс запишется false если условие не выполнится

спс за это замечание, вот это я был удивлён, что если компоненту так рендеришь никакого false там нет, а если тоже самое делаешь только в классах, появляется false!
Исправил

2022-12-14 21:51 UTC, sokol-rc approved these changes
Всё норм!

2022-12-14 21:51 UTC, sokol-rc commented on packages/client/src/pages/screen-game-over/screen-game-over.module.scss
> +    font-weight: 400;
да, ты прав

2022-12-14 21:54 UTC, thechertan commented on packages/client/src/pages/screen-game-over/screen-game-over.module.scss
> +  flex-direction: column;
> А зачем column если 1 потомок?

Исправил

2022-12-14 21:56 UTC, thechertan commented on packages/client/src/pages/screen-game-over/screen-game-over.module.scss
> +    flex-direction: row;
> row initial значение для flex-direction Отдельно указывать излишне

Привык явно указывать. Исправил

2022-12-14 22:22 UTC, thechertan commented on packages/client/src/pages/screen-game-over/screen-game-over.tsx
> +    }, { P1: 0, P2: 0 })
> Расчет totalScore лучше оставить на стороне бизнес логики. Пусть вью занимается простым отображением. Во входящем объекте данных просто добавь totalScore для каждого игрока

Хорошее замечание, спс исправил

2022-12-14 22:22 UTC, thechertan commented on packages/client/src/pages/screen-game-over/screen-game-over.tsx
> +          <p className={styles['players-stats__pts-count']}>{value.P1 ? (value.P1 * (100 * (index + 1))) : 0}</p>
> Вычисления лучше вынести в переменную. А еще лучше получать сразу готовые данные

Исправил

2022-12-17 23:18 UTC, merged