Реализована страница форума с комментариями
5dev-team/BattleCity pull request #16
Opened 2022-12-11 18:30 UTC by freeweball

2022-12-12 08:20 UTC, EzhikTT approved these changes
Все ок

2022-12-13 12:32 UTC, lmm1ng commented on packages/client/src/App.tsx
> +        <Route path={RoutePaths.COMMENTS} element={<Comments />} />
Лучше указывать роут с ошибкой в самом низу (`path: '*'`)

2022-12-13 12:32 UTC, lmm1ng commented on packages/client/src/components/UI/nes-textarea/nes-textarea.tsx
> +    <div className={`${styles['textarea-wrapper']}`}>
Можно не использовать шаблонные строки, если нет никакого форматирования

2022-12-13 12:32 UTC, lmm1ng commented on packages/client/src/pages/comments/comments.module.scss
> +.comments-title {
Для красоты можно использовать нейминг классов по БЭМу

2022-12-13 12:32 UTC, lmm1ng commented on packages/client/src/pages/comments/comments.tsx
> +  <div className={`${styles['comments']}`}>
Тут и внизу тоже шаблонные строки

2022-12-13 12:32 UTC, lmm1ng commented on packages/client/src/pages/comments/comments.tsx
> +  templateThem.content && setComment([...comments, templateComment])
Я бы написал через условный оператор, нежели через логическое замыкание

2022-12-13 12:32 UTC, lmm1ng commented on packages/client/src/pages/comments/comments.tsx
> +    <li key={id} className={`${styles['comments-item']}`}>
Лучше не использовать `id` в качестве ключа

2022-12-13 12:32 UTC, lmm1ng commented on packages/client/src/pages/forum/forum.tsx
>          .map((el, id) => <div key={id} className={`${styles['forum-header-item']}`}>{el}</div>)
То же про `id`

2022-12-13 12:32 UTC, lmm1ng commented on packages/client/src/pages/forum/forum.tsx
>      const addThemes = (themes: Array<ForumThemesType>) => {
Тут лучше использовать `useMemo`

2022-12-17 21:19 UTC, sokol-rc reviewed
Все что есть, классно!

Есть 1 замечание по поводу проверки id в url
Если перейти по ссылкам:
```
http://localhost:3000/forum/2/WorldOfTank
и
http://localhost:3000/forum/22/WorldOfTank
```
То будет одинаковый контент

2022-12-20 11:45 UTC, sokol-rc requested changes
Спасибо за работу!
Есть пара критичных вещей в package.json
В остальном всё ок

2022-12-20 11:45 UTC, sokol-rc commented on package.json
> +    "react-input-emoji": "^4.3.0"
Пара вопросов:
Зачем нам пакет i?
Зачем нам пакет npm?
и почему это установлено в корне проекта?
Надо убрать крышечки ^.

У нас разделение идет на client и server, Соответственно пакеты, нужные на клиенте, устанавливаются в клиент

например так `lerna add -D react-input-emoji --scope:client`

2022-12-20 11:45 UTC, sokol-rc commented on packages/client/src/App.tsx
> +import Comments from './pages/comments'
Мы везде используем alias `@` - src/

2022-12-20 11:45 UTC, sokol-rc commented on packages/client/src/pages/comments/comments.tsx
> +export interface CommentsProps {
Договорились, что интерфейсы начинаются с I.

2022-12-20 11:45 UTC, sokol-rc commented on packages/client/src/index.scss
> +.react-emoji div {
Лучше не использоваться селектор элемента в качестве потомка.
Браузер сначала найдет все div на странице, а уже потом будет искать внутри `.react-emoji`
Подробнее тут: [ссылка](https://habr.com/ru/post/445292/)

В нашем случае это почти не влияет на производительность.

2023-01-23 09:27 UTC, EzhikTT commented on packages/client/src/components/UI/smiles-block/smiles-block.tsx
> +      <li><img src='/src/assets/smiles/smile-1.png' width='30' height='30'/></li>
Здесь можно было бы использовать какой-нибудь красивый `Array(7).fill().map((_, id) => <li><img src=`/src/assets/smiles/smile-${id + 1}.png` width='30' height='30'/></li>)`. Не оптимально, но более программно)

2023-01-23 09:29 UTC, EzhikTT commented on packages/client/src/pages/comments/comments.module.scss
> +.comments-title {
Или семантическую верстку. Стиль-модно-молодежно

2023-01-23 09:49 UTC, EzhikTT requested changes

2023-01-23 09:49 UTC, EzhikTT commented on packages/client/src/components/UI/nes-textarea/nes-textarea.tsx
> +        className={`is-${variant} nes-textarea ${styles['textarea-input']}`}
Если `variant` нет, то стиль получается невалидный (`is-undefined`). Так и должно быть?

2023-01-24 05:08 UTC, merged