Task 66 Настройка окружения jest
5dev-team/BattleCity pull request #19
Opened 2022-12-14 17:20 UTC by thechertan

### Какую задачу решаем
Настройка окружения jest
 -Реализован тест на то что App рендерится, используется:
   react-test-renderer для того, чтобы использовать поверхностный render
   redux-mock-store для того, чтобы мокать наш store 

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2022-12-16 13:05 UTC, Underwindow reviewed
В целом всё ок, спасибо за работу!

2022-12-16 13:05 UTC, Underwindow commented on packages/client/src/components/UI/nes-input/nes-input.tsx
>    HTMLInputElement, INesInputProps
Лучше вернуть как было. Изменение компонента nes-input не относится к решаемой задаче.

2022-12-16 13:07 UTC, thechertan commented on packages/client/src/components/UI/nes-input/nes-input.tsx
>    HTMLInputElement, INesInputProps
Насчет того чтобы вернуть согласен, верну.
Но когда будите тестировать NesInput все равно сделаете так как сделано тут

2022-12-16 13:08 UTC, tsforge commented on packages/client/src/components/UI/nes-input/nes-input.tsx
>    HTMLInputElement, INesInputProps
> Лучше вернуть как было. Изменение компонента nes-input не относится к решаемой задаче.

Насчет того чтобы вернуть согласен, верну.
Но когда будите тестировать NesInput все равно сделаете так как сделано тут

2022-12-16 13:10 UTC, Underwindow commented on packages/client/src/components/UI/nes-input/nes-input.tsx
>    HTMLInputElement, INesInputProps
Спасибо, да, в моём PR логики профиля сделано как у тебя через forwardRef, так что всё в порядке!

2022-12-16 21:24 UTC, sokol-rc requested changes

2022-12-16 21:24 UTC, sokol-rc commented on packages/server/package.json
> +    "redux-mock-store": "^1.5.4",
Этот пакет должен быть в сервере?

2022-12-16 21:24 UTC, sokol-rc commented on packages/client/package.json
> +    "redux-mock-store": "^1.5.4",
Лучше убрать крышечки

2022-12-16 22:55 UTC, thechertan commented on packages/server/package.json
> +    "redux-mock-store": "^1.5.4",
> Этот пакет должен быть в сервере?

Да, если у тебя получится замокать стор самому, то круто, у меня не получилось.

2022-12-16 22:56 UTC, thechertan commented on packages/client/package.json
> +    "redux-mock-store": "^1.5.4",
> Лучше убрать крышечки

мда, забыл, спс!

2022-12-16 22:59 UTC, thechertan commented on packages/client/src/components/UI/nes-input/nes-input.tsx
>    HTMLInputElement, INesInputProps
> Спасибо, да, в моём PR логики профиля сделано как у тебя через forwardRef, так что всё в порядке!

Исправи

2022-12-16 23:00 UTC, thechertan commented on packages/client/package.json
> +    "redux-mock-store": "^1.5.4",
> Лучше убрать крышечки

Исправил

2022-12-16 23:03 UTC, thechertan commented on packages/client/src/components/UI/nes-input/nes-input.tsx
>    HTMLInputElement, INesInputProps
![image](https://user-images.githubusercontent.com/84693047/208202714-fce75d56-a2b1-4656-9efc-45b2be8d59a5.png)

Ругается говорит исправить надо

2022-12-17 22:59 UTC, sokol-rc commented on packages/server/package.json
> +    "redux-mock-store": "^1.5.4",
Вопрос чуть о другом.
Есть клиент и сервер
redux, стор это на клиенте, зачем этот пакет на сервере?

2022-12-18 00:05 UTC, thechertan commented on packages/server/package.json
> +    "redux-mock-store": "^1.5.4",
> Вопрос чуть о другом. Есть клиент и сервер redux, стор это на клиенте, зачем этот пакет на сервере?

Понял, спс за замечание исправлю :)

2022-12-18 00:10 UTC, thechertan commented on packages/server/package.json
> +    "redux-mock-store": "^1.5.4",
Исправил

2022-12-20 18:41 UTC, sokol-rc approved these changes
Всё ок!

2022-12-20 18:51 UTC, thechertan commented
Ребят насчет фейкового теста. 
Фейковый тест необходимо будет удалить как только появится первый нормальный тест.
Пришлось изменить некоторые моменты в tsconfig.json а так же в его node.
Причиной оказался всех ошибок оказался esModuleInterop, спасибо Евгению за подсказку.
Теперь насчёт esModuleInterop, что он делает, предлагаю прочитать https://habr.com/ru/post/542234/ в крации, в es5 не было деструктуризации как таковой, все использовали функции в виде объекта, то есть так React.function.
С появление ES6 он же ES2016...22 у нас появилась возможность деструктуризации функций из необходимого файла.
esModuleInterop в положении false ссылался на undefined с использованием функций такого ввида React.function
esModuleInterop в положении true позволяет импортировать в ES6 синтаксисе ESNext импортировать так же как и в ES5

2022-12-20 19:16 UTC, merged

2023-02-21 11:28 UTC, EzhikTT commented
Все ок