feat: task-76-create-hoc and hook for protect route
5dev-team/BattleCity pull request #21
Opened 2022-12-16 22:53 UTC by thechertan

### Какую задачу решаем
 Написать собственный Hook или HOC авторизации

### Скриншоты/видяшка (если есть)
![image](https://user-images.githubusercontent.com/84693047/208201779-1e497eac-394c-4ae6-a5e6-79846eacae90.png)

### TBD (если есть)

2022-12-18 01:12 UTC, sokol-rc reviewed
Шикарный хук!

Есть пара вопросов в комментариях

2022-12-18 01:12 UTC, sokol-rc commented on packages/client/src/App.tsx
> +        </Route>
А для чего несколько раз указывать роуты ошибок?

2022-12-18 01:12 UTC, sokol-rc commented on packages/client/src/App.tsx
> +        </Route>
Если не авторизован, как попасть на страницу ошибки или любую другую?
например 
```
/sadkasdk
/sign-up
```
редиректит на sign-in

2022-12-18 01:20 UTC, sokol-rc commented on packages/client/src/store/slices/auth/index.ts
> +      state.isLoggedIn = false
А почему зачем надо разлогинивать юзера, если не пришли данные юзера?

2022-12-18 01:53 UTC, thechertan commented on packages/client/src/App.tsx
> +        </Route>
> Если не авторизован, как попасть на страницу ошибки или любую другую? например
> 
> ```
> /sadkasdk
> /sign-up
> ```
> 
> редиректит на sign-in

Знал о этой проблеме, решил её оставить, т.к делать хук через чур умный, который знает все роуты не стал, но видимо сделаю

2022-12-18 01:56 UTC, thechertan commented on packages/client/src/store/slices/auth/index.ts
> +      state.isLoggedIn = false
> А почему зачем надо разлогинивать юзера, если не пришли данные юзера?

любой ответ 400 и < означает reject, а это в свою очередь означает что либо протух токен авторизации либо ключ в env сменили либо сайт перегружен и не может стабильно отдавать данные, поэтому стоит его разлогинивать

2022-12-18 01:59 UTC, thechertan commented on packages/client/src/App.tsx
> +        </Route>
> А для чего несколько раз указывать роуты ошибок?

сделал так, потому что пытался достучаться до 404, как раз /sadkasdk но не удалось, а так указывать посчитал логичным.

2022-12-18 04:30 UTC, thechertan commented on packages/client/src/App.tsx
> +        </Route>
> Если не авторизован, как попасть на страницу ошибки или любую другую? например
> 
> ```
> /sadkasdk
> /sign-up
> ```
> 
> редиректит на sign-in

Не баг а фича, зачем пользователю куда то заходить если он разлогинен, а вообще его просто постоянно ридиректит на SIGNIN, ввиду особенностей RR V6.
  Просидел пол ночи пытался решить, не получается, нужен хелп
  С 5 роутером и начальным 6 когда он только вышел я бы справился с задачей, сейчас не могу, нужен ХЕЛП.

2022-12-18 05:30 UTC, thechertan commented on packages/client/src/App.tsx
> +        </Route>
Либо надо передавать значение loggedIn в два компонента, я про SIGNIN и SIGNUP и там уже решать рендерить компонент или делать ридирект, зная нашу команду кто то начнёт орать не лезь в другие компоненты и ничего там не делай.

2022-12-18 05:35 UTC, thechertan commented on packages/client/src/App.tsx
> +        </Route>
Если интересна моя позиция, она така же как у яндекса:
![image](https://user-images.githubusercontent.com/84693047/208283193-a7f5ebd2-9fe8-4a06-9f90-35600517421a.png)

2022-12-18 09:40 UTC, lmm1ng commented on packages/client/src/store/slices/auth/index.ts
> +      state.isLoggedIn = false
а что если сессия протухла и пришел код 401 с бэка? Получается рассинхрон состояний

2022-12-18 16:55 UTC, thechertan commented on packages/client/src/store/slices/auth/index.ts
> +      state.isLoggedIn = false
> а что если сессия протухла и пришел код 401 с бэка? Получается рассинхрон состояний

401 Это тоже reject

2022-12-19 08:07 UTC, EzhikTT requested changes

2022-12-19 08:07 UTC, EzhikTT commented on packages/client/src/store/slices/auth/index.ts
> +      state.isLoggedIn = false
А если будет 403(4)? Или 50х? Это ошибки сервера и никак не связаны с авторизацией, зачем разлогинивать пользователя, если на сервере что-то упало?

2022-12-19 08:07 UTC, EzhikTT commented on packages/client/src/pages/game/game.tsx
> +  console.log('game')
Лог здесь нужен?

2022-12-19 08:07 UTC, EzhikTT commented on packages/client/src/App.tsx
> +          <Route path={RoutePaths.SIGNIN} element={<SignIn />} />
А почему где-то первым идет `element`, а где-то `path`?

2022-12-19 13:54 UTC, thechertan commented on packages/client/src/App.tsx
> +          <Route path={RoutePaths.SIGNIN} element={<SignIn />} />
> А почему где-то первым идет `element`, а где-то `path`?
ProtectRoute это HOC над дочерними элементами, тут хок чуток другой в реализации в отличии от RR5 версии

2022-12-19 13:59 UTC, thechertan commented on packages/client/src/store/slices/auth/index.ts
> +      state.isLoggedIn = false
> А если будет 403(4)? Или 50х? Это ошибки сервера и никак не связаны с авторизацией, зачем разлогинивать пользователя, если на сервере что-то упало?

Так а если на сервере упало основное API откуда идёт отправная точка, то видимо BackEnd пьёт кофА и ими в этотм момент нужно перестать его пить и заняться делом, конечно можно перекинуть всё в локальное хранилище как вариант но если сервак заглючит и упадёт то возможны рассинхроны, грубо говоря палка двух концов, какой вариант выбрать я думаю тут выбирает сам разработчик.

2022-12-19 20:29 UTC, thechertan commented on packages/client/src/pages/game/game.tsx
> +  console.log('game')
> Лог здесь нужен?

нет, не нужен

2022-12-20 21:52 UTC, EzhikTT commented on packages/client/src/App.tsx
> +          <Route path={RoutePaths.SIGNIN} element={<SignIn />} />
Вопросы был в том, что порядок разный. Скорее стилистический вопрос однообразия был, а не замечание

2022-12-20 21:53 UTC, EzhikTT commented on packages/client/src/store/slices/auth/index.ts
> +      state.isLoggedIn = false
С точки зрения ревью кода, можно оставить и так, НО нужно, чтобы вы в команде решили как ведет себя приложение при таких ошибках сервера

2022-12-20 21:54 UTC, EzhikTT requested changes

2022-12-20 21:54 UTC, EzhikTT commented on packages/client/src/pages/game/game.tsx
> +  console.log('game')
Значит его нужно удалить)

2022-12-22 14:09 UTC, Underwindow approved these changes
Всё ок! Классно реализовано!

2022-12-24 23:57 UTC, thechertan commented on packages/client/src/store/slices/auth/index.ts
> +      state.isLoggedIn = false
> С точки зрения ревью кода, можно оставить и так, НО нужно, чтобы вы в команде решили как ведет себя приложение при таких ошибках сервера

посли синка с командой решили разлогинивать человека только при 401 статуса

2022-12-24 23:58 UTC, thechertan commented on packages/client/src/store/slices/auth/index.ts
> +      state.isLoggedIn = false
> > С точки зрения ревью кода, можно оставить и так, НО нужно, чтобы вы в команде решили как ведет себя приложение при таких ошибках сервера
> 
> после синка с командой решили разлогинивать человека только при 401 статуса

2022-12-25 00:01 UTC, thechertan commented on packages/client/src/pages/game/game.tsx
> +  console.log('game')
> Значит его нужно удалить)

удалил

2022-12-26 06:51 UTC, EzhikTT approved these changes
Теперь ок)

2022-12-26 15:01 UTC, lmm1ng approved these changes
Этот момент поправишь и можно лить :)

2022-12-26 15:01 UTC, lmm1ng commented on packages/client/src/store/slices/auth/index.ts
> +      status === 401 ? state.isLoggedIn = false : state.isLoggedIn = true
Можно написать попроще.
Например, что-то в этом роде:
`state.isLoggedIn = status !== 401`

2022-12-30 00:15 UTC, sokol-rc approved these changes
Все супер

2022-12-30 00:15 UTC, sokol-rc commented on packages/client/src/store/slices/auth/index.ts
> +      const result: number | string = error.message === 'Cookie is not valid' ? 401 : error.code || 401
Круто, что смог так сократить строку, но тяжело читать.
Лучше разбить на пару условий.

2023-01-14 18:49 UTC, merged