Task 64 service-worker и оффлайн режим
5dev-team/BattleCity pull request #32
Opened 2022-12-25 01:13 UTC by sokol-rc

### Какую задачу решаем
Внедрить в проект Service Workers и возможность запускать сервис без доступа к интернету

Для проверки, необходимо собрать проект, затем в файле dist/sw.js исправить пути к файлам внутри dist с новым хешем.

2022-12-26 06:57 UTC, EzhikTT commented
Нужно решить конфликты, потом чекну

2022-12-27 11:24 UTC, EzhikTT requested changes
Еще можно лок файл дропнуть)

2022-12-27 11:24 UTC, EzhikTT commented on packages/client/src/App.tsx
> +        <Route path='/offline' element={<Offline />} />
Почему этот путь не в константе?

2022-12-27 12:32 UTC, sokol-rc commented on packages/client/src/App.tsx
> +        <Route path='/offline' element={<Offline />} />
Согласен с замечанием, не стал исправлять, т.к. наставник предложил нам другую стратегию оффлайна и мы договорились поменять ее в этом спринте. Там не будет этой страницы

2022-12-29 14:38 UTC, EzhikTT commented on packages/client/src/App.tsx
> +        <Route path='/offline' element={<Offline />} />
Оки

2022-12-29 14:39 UTC, EzhikTT approved these changes

2022-12-29 14:43 UTC, merged