Task 87 добавить противников в игру
5dev-team/BattleCity pull request #41
Opened 2023-01-27 02:00 UTC by sokol-rc

### Какую задачу решаем
- Добавить противников в игру;
- Добавить "debug" режим в игру;
- Добавить подсчет очков, складировать в store;
- Отправлять полученные очки в таблицу лидеров, если текущий рекорд больше предыдущего;

2023-01-30 08:50 UTC, EzhikTT commented on packages/client/src/components/UI/nes-file-input/nes-file-input.tsx
> +              {plain && (plainText ?? 'Load avatar')}
Можно было объединить эти две строчки через тернарный оператор `plain ? (plainText ?? 'Load avatar') : 'Choose File'`

2023-01-30 08:51 UTC, EzhikTT commented on packages/client/src/components/UI/nes-file-input/nes-file-input.tsx
> +              if (onChange) {
Функции больше одного действия лучше выносить из jsx в тело коммонента

2023-01-30 08:58 UTC, EzhikTT commented on packages/client/src/game/core/stage/stage.ts
> +        if (        a.left < b.right &&
Отступ не красивый

2023-01-30 08:59 UTC, EzhikTT commented on packages/client/src/game/core/view/view.ts
> +          // Включение дебага НЕ УДАЛЯТЬ! stage.getCollision
`TODO` сюда бы еще добавить

2023-01-30 09:01 UTC, EzhikTT commented on packages/client/src/game/helpers/helpers.ts
> +  if (keys.has('ArrowUp')) {
Можно было заменить на `if..elseif..else`, где в конца возвращалось бы `Direction.UP`, тк по итогу оно дефолтное значение получается

2023-01-30 09:02 UTC, EzhikTT commented on packages/client/src/game/helpers/helpers.ts
> +      return -1
Если это не заглушка, можно было по блокам на основе возвращаемого значения объединить

2023-01-30 09:03 UTC, EzhikTT commented on packages/client/src/pages/comments/comments.tsx
> +            return new Promise(resolve => resolve(evt))
Можно было вынести в функцию в тело компонента и сделать на `async/await`

2023-01-30 09:06 UTC, EzhikTT requested changes
Почему где-то `kebab-case` в названиях файлов и папок?

2023-02-01 00:23 UTC, thechertan commented
> Почему где-то `kebab-case` в названиях файлов и папок?

так решили

2023-02-01 00:27 UTC, thechertan commented on packages/client/src/game/core/view/view.ts
> +          // Включение дебага НЕ УДАЛЯТЬ! stage.getCollision
> `TODO` сюда бы еще добавить

учтём :)

2023-02-01 00:29 UTC, thechertan commented on packages/client/src/game/helpers/helpers.ts
> +      return -1
> Если это не заглушка, можно было по блокам на основе возвращаемого значения объединить

На сколько я помню эту функцию я писал.
Записал в TODO, в дальнейшем если будет время переделаю

2023-02-01 00:29 UTC, thechertan commented on packages/client/src/game/helpers/helpers.ts
> +  if (keys.has('ArrowUp')) {
На сколько я помню эту функцию я писал.
Записал в TODO, в дальнейшем если будет время переделаю

2023-02-01 00:30 UTC, thechertan commented on packages/client/src/game/helpers/helpers.ts
> +  if (keys.has('ArrowUp')) {
> Можно было заменить на `if..elseif..else`, где в конца возвращалось бы `Direction.UP`, тк по итогу оно дефолтное значение получается

> На сколько я помню эту функцию я писал. Записал в TODO, в дальнейшем если будет время переделаю

2023-02-03 07:53 UTC, EzhikTT approved these changes
Все ок

2023-02-08 17:52 UTC, merged