Task 76 92 create and setting back end
5dev-team/BattleCity pull request #42
Opened 2023-01-27 15:10 UTC by thechertan

### Какую задачу решаем

Все ручки ведут localhost:3001, когда появится заменить на доменное имя! Во всех ручках необходимо быть авторизованным иначе получите 403 с вертушки :D

ручка: /api/v1/forum

method get возвращает:

[
    {
        "id": 2,
        "authorId": 23972,
        "title": "dsadsadas",
        "countMessage": 0,
        "lastMessageDate": null,
        "lastMessageId": null
    },
    {
        "id": 3,
        "authorId": 23972,
        "title": "one",
        "countMessage": 0,
        "lastMessageDate": null,
        "lastMessageId": null
    }
]

method post возвращает: 

{
    "id": 3,
    "authorId": 23972,
    "title": "one",
    "createdAt": 1674323281
}

body: {"title": "one"}

method DELETE возвращает 

{
    "message": "Форум удален успешно"
}

body: {"id": 1 }

method PATH возвращает: 

{
    "id": 2,
    "authorId": 23972,
    "title": "dsadsadas",
    "createdAt": 1674323280
}

body: {"id": 2 , "title": "dsadsadas"}

method get '/api/v1/forum/:idForum' возвращает:

[
    {
        "id": 8,
        "authorId": 23972,
        "content": "dsadasd",
        "rootPost": null,
        "createdAt": 1674593351
    },
    {
        "id": 9,
        "authorId": 23972,
        "content": "dsadasd",
        "rootPost": null,
        "createdAt": 1674593352
    },
]

ручка: /api/v1/forum/post

method: post возвращает:

{
    "id": 11,
    "authorId": 23972,
    "content": "dsadasd",
    "forumId": 2,
    "rootPost": null,
    "createdAt": 1674593354
}

body: {"content": "dsadasd", "forumId": 2}

method: DELETE возвращает: 

{
    "message": "Пост удален успешно"
}

method: PATH возвращает:

{
    "id": 9,
    "authorId": 23972,
    "content": "ppc",
    "rootPost": null
}

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-01-28 15:13 UTC, lmm1ng commented on DockerFile
> +FROM node:$NODE_VERSION-buster as base
почему не alpine?

2023-01-28 15:13 UTC, lmm1ng commented on DockerFile
> +COPY . .
Зачем перемещать всю директорию со всеми node_modules и ненужными файлами? Нужно оптимизировать

2023-01-28 15:13 UTC, lmm1ng commented on packages/server/controllers/forum/forum.ts
> +import type { NextFunction, Request, Response } from 'express'
По-хорошему, контроллер должен быть максимально тонким. Всю работы с БД и прочим лучше вынести в сервис

2023-01-28 15:13 UTC, lmm1ng commented on packages/server/controllers/forum/forum.ts
> +    delete data.dataValues.updatedAt
Скорее всего наличие и содержимое полей дат можно настроить в конфиге ORM таблицы

2023-01-28 15:13 UTC, lmm1ng commented on packages/server/controllers/forum/forum.ts
> +    const forum: Model<IForum>[] = await Forum.findAll({
Тут лучше назвать переменную `forums`, потому что ниже идёт `forum.map`. Не очень логично

2023-01-28 15:13 UTC, lmm1ng commented on packages/server/controllers/forum/forum.ts
> +            await ForumPosts.destroy({ where: { id } })
Неужели нужно руками все удалять? Нужны связи между таблицами через FK

2023-01-28 20:39 UTC, thechertan commented on DockerFile
> +FROM node:$NODE_VERSION-buster as base
Вроде как весит меньше

2023-01-28 20:40 UTC, thechertan commented on DockerFile
> +COPY . .
> Зачем перемещать всю директорию со всеми node_modules и ненужными файлами? Нужно оптимизировать

в dockerignore указал
 .git
node_modules
npm-debug
dist
Поэтому туда никак не попадет nodeModules, но спасибо что обратил внимание, нужно туда добавить еще логи запросов!

2023-01-29 14:15 UTC, thechertan commented on packages/server/controllers/forum/forum.ts
> +    delete data.dataValues.updatedAt
> Скорее всего наличие и содержимое полей дат можно настроить в конфиге ORM таблицы

к сожалению судя по документации поля 'updatedAt', 'createdAt' нельзя исключать из таблицы во время создания, поэтому принято решения удалить таким способом, 'updatedAt', 'createdAt'  эти поля нужны и описаны в модели.

2023-01-29 14:31 UTC, thechertan commented on packages/server/controllers/forum/forum.ts
> +    const forum: Model<IForum>[] = await Forum.findAll({
> Тут лучше назвать переменную `forums`, потому что ниже идёт `forum.map`. Не очень логично

Согласне, спс

2023-01-29 14:36 UTC, thechertan commented on packages/server/controllers/forum/forum.ts
> +            await ForumPosts.destroy({ where: { id } })
> Неужели нужно руками все удалять? Нужны связи между таблицами через FK

да как ты и написал, есть onDelete
https://sequelize.org/docs/v6/other-topics/hooks/#hooks-for-cascade-deletes

2023-01-29 23:44 UTC, thechertan commented on DockerFile
> +FROM node:$NODE_VERSION-buster as base
> почему не alpine?

переделал на alpine, всё таки alpine весит меньше, спс!

2023-01-30 09:40 UTC, EzhikTT commented on packages/server/controllers/forum/forum.ts
> +import type { NextFunction, Request, Response } from 'express'
Контроллер может быть как тонким, так и толстым. Вопрос как вы внутри команды договорились

2023-01-30 09:46 UTC, EzhikTT commented on packages/server/init/index.ts
> +  logging: false // отключаем логирование в консоле!
`консолИ` // сори

2023-01-30 09:48 UTC, EzhikTT requested changes

2023-01-30 09:48 UTC, EzhikTT commented on packages/server/controllers/forum/forum.ts
> +    delete data.dataValues.updatedAt
А зачем вообще трогать эти поля?

2023-01-30 10:40 UTC, thechertan commented on packages/server/init/index.ts
> +  logging: false // отключаем логирование в консоле!
:D

2023-01-30 14:39 UTC, thechertan commented on packages/server/controllers/forum/forum.ts
> +    delete data.dataValues.updatedAt
> А зачем вообще трогать эти поля?

А почему их нельзя трогать?

2023-01-31 13:43 UTC, lmm1ng approved these changes

2023-02-01 11:09 UTC, merged

2023-02-21 11:30 UTC, EzhikTT commented on packages/server/controllers/forum/forum.ts
> +    delete data.dataValues.updatedAt
Зачем удалять поле даты обновления? Оно чем-то мешает?

2023-02-21 11:30 UTC, EzhikTT commented
Кроме вопроса про поле, все ок

2023-02-21 17:52 UTC, sokol-rc commented
@EzhikTT 
Момент с полем исправлен в этом [PR](https://github.com/5dev-team/BattleCity/pull/45)