Issue 101 fix game bugs
5dev-team/BattleCity pull request #49
Opened 2023-02-10 14:56 UTC by Underwindow

### Исправление багов в игре

1. Танки противников застревают друг в друге. Должны врезаться и разъезжаться.
2. Танк игрока или танк противника могут застрять внутри вражеского (или танка игрока) при появлении его в мире. Должны при появлении танка противника (или игрока), если на этом месте уже находится танк - столкновения не происходит, и они могут передвигаться друг на друге (наслаиваясь), пока не разъедутся, после этого столкновения работают в штатном режиме.
3. При выстреле вражеского танка, пуля этого танка пролетая сквозь другого вражеского танка вызывает у него (эпилепсию?) коллизии и танк начинает крутиться, пока пуля находится "на" нем. Должны пули пролетать и не вызывать никаких действия у танка противника

2023-02-12 16:04 UTC, EzhikTT commented on packages/client/src/game/core/bullet/bullet.ts
> +        c => this.shouldCollideWith(c) && c !== this.tank
А мб стоит поменять условия местами? У какого условия больше шансов на срабатывание? Оптимальней и красивей ставить условия по частоте срабатывания

2023-02-12 16:09 UTC, EzhikTT commented on packages/client/src/game/core/game-engine/game-engine.ts
> +  public controllerMode: ControllerType
Возможно, стоило бы типы писать по подобию интерфейсов, например `TController`

2023-02-12 16:17 UTC, EzhikTT requested changes

2023-02-12 16:17 UTC, EzhikTT commented on packages/client/src/game/core/tank/tank.ts
> +    console.log(!this.bullet)
Зачем оно тут осталось?)

2023-02-12 16:17 UTC, EzhikTT commented on packages/client/src/game/core/sprite/sprite.ts
> +  async load(): Promise<ImageLoader> {
А зачем тут пометка `async`, если нигде нет `await`?

2023-02-12 16:17 UTC, EzhikTT commented on packages/client/src/game/core/event-bus/event-bus.ts
> +    const onceFn = (...res: unknown[]) => {
Почему тут `unknown`, а не конкретный тип?

2023-02-12 16:17 UTC, EzhikTT commented on packages/client/src/game/core/bullet/bullet.ts
> +        collisions.forEach(c => ((c as unknown) as IHitable).hit(this))
Почему тут `.forEach()` вместо нормального цикла?

2023-02-12 16:29 UTC, sokol-rc commented on packages/client/src/game/core/bullet/bullet.ts
> +        collisions.forEach(c => ((c as unknown) as IHitable).hit(this))
А какие преимущества будут тут у нормального цикла?

2023-02-13 10:38 UTC, merged

2023-02-14 13:36 UTC, EzhikTT commented on packages/client/src/game/core/bullet/bullet.ts
> +        collisions.forEach(c => ((c as unknown) as IHitable).hit(this))
Как минимум [производительность](https://leanylabs.com/blog/js-forEach-map-reduce-vs-for-for_of/) и актуальность

2023-02-14 13:48 UTC, sokol-rc commented on packages/client/src/game/core/bullet/bullet.ts
> +        collisions.forEach(c => ((c as unknown) as IHitable).hit(this))
стоит ли задумываться о данной микрооптимизации в угоду читаемости/семантике в 2023?.
Куда большую выгоду по оптимизации можно получить, уменьшив вес некоторых картинок, которые сейчас в проекте весят больше 1 мб. Импортировать только FC из реакт в компоненты, если больше ничего не используем, вместо React.FC.

2023-02-20 13:48 UTC, EzhikTT commented on packages/client/src/game/core/bullet/bullet.ts
> +        collisions.forEach(c => ((c as unknown) as IHitable).hit(this))
Стоит использовать решения, которые являются качественнее и современней. Вы жеж не пишите на прототипах и ES5-

2023-02-20 23:53 UTC, sokol-rc commented on packages/client/src/game/core/bullet/bullet.ts
> +        collisions.forEach(c => ((c as unknown) as IHitable).hit(this))
Тогда совсем не понял первый комментарий, Что есть обычный цикл? for (let i = 0; i < arr.length; i++) 
И почему он современнее чем forEach?