Верстка страницы leaderboard
5dev-team/BattleCity pull request #5
Opened 2022-11-27 17:58 UTC by sokol-rc

Верстка страницы leaderboard
доступна по пути "/leaderboard"

+ новый UI-компонент "nes-avatar"

![изображение](https://user-images.githubusercontent.com/83005607/204151792-a63502a6-84a8-47b6-8ab8-64a19adae5b5.png)

2022-11-27 18:48 UTC, lmm1ng commented on packages/client/src/components/UI/nes-avatar/nes-avatar.tsx
> +interface IAvatar extends ButtonHTMLAttributes<HTMLImageElement> {
При чем здесь кнопка?

2022-11-27 18:48 UTC, lmm1ng commented on packages/client/src/components/UI/nes-avatar/nes-avatar.tsx
> +  alt?: string
Если выставить интерфейс правильно, то alt указывать не нужно, так как он уже есть в наследуемом интерфейсе

2022-11-27 18:48 UTC, lmm1ng commented on packages/client/src/components/UI/nes-avatar/nes-avatar.tsx
> +    <img className={`nes-avatar is-${size} ${rounded ? 'is-rounded' : ''}${styles['avatar']}`}
Пробел перед стилями? Если аватар будет скруглен, то будет `is-roundedavatar_hash`

2022-11-27 18:48 UTC, lmm1ng commented on packages/client/src/components/UI/nes-avatar/nes-avatar.tsx
> +    />
тут лучше заспредить остальные пропсы

2022-11-27 18:48 UTC, lmm1ng commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +            <div className={`${styles['table__col']} ${styles['table__col--second-color']}`}>Username</div>
Давай создадим мок с данными лидерборда и отрисуем все циклом? Подготовимся к внедрению апи и уменьшим код

2022-11-27 18:48 UTC, lmm1ng commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +        <div className={`${styles['leaderboard__table']} ${styles['table']}`}>
Почему не взял `<table>`?

2022-11-27 18:48 UTC, lmm1ng commented on packages/client/src/pages/leaderboard/leaderboard.module.scss
> +  flex-direction: column;
Зачем менять ось если ребенок один?

2022-11-27 18:48 UTC, lmm1ng commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +            <NesButton variant='primary' fullWidth onClick={() => navigate('/')}>
У нас есть компонент ссылки для навигации между компонентами. Или ты хочешь, чтобы это была именно кнопка?

2022-11-28 11:41 UTC, sokol-rc commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +            <NesButton variant='primary' fullWidth onClick={() => navigate('/')}>
Да, хотел оставить именно кнопку

2022-11-28 11:41 UTC, sokol-rc commented on packages/client/src/pages/leaderboard/leaderboard.module.scss
> +  flex-direction: column;
Нет нужды
Исправлено

2022-11-28 11:42 UTC, sokol-rc commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +            <div className={`${styles['table__col']} ${styles['table__col--second-color']}`}>Username</div>
Исправлено

2022-11-28 11:42 UTC, sokol-rc commented on packages/client/src/components/UI/nes-avatar/nes-avatar.tsx
> +    />
Исправлено

2022-11-28 11:42 UTC, sokol-rc commented on packages/client/src/components/UI/nes-avatar/nes-avatar.tsx
> +    <img className={`nes-avatar is-${size} ${rounded ? 'is-rounded' : ''}${styles['avatar']}`}
Исправлено

2022-11-28 11:42 UTC, sokol-rc commented on packages/client/src/components/UI/nes-avatar/nes-avatar.tsx
> +  alt?: string
Исправлено

2022-11-28 11:42 UTC, sokol-rc commented on packages/client/src/components/UI/nes-avatar/nes-avatar.tsx
> +interface IAvatar extends ButtonHTMLAttributes<HTMLImageElement> {
Исправлено на ImgHTMLAttributes

2022-11-28 13:03 UTC, EzhikTT commented on packages/client/src/App.tsx
> +        <Route path='/leaderboard' element={<LeaderBoard />} />
Для красоты можно константы пути

2022-11-28 13:12 UTC, EzhikTT requested changes

2022-11-28 13:12 UTC, EzhikTT commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +  const userRows = userScore.map((user, index) => {
А нельзя это в хук `useMemo`  обернуть?

2022-11-28 13:12 UTC, EzhikTT commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +        <div className={`${styles['leaderboard__table']} ${styles['table']}`}>
Разницы между `div` и `table` нет, если размеры не сильно большие. По стилям, как я понял, они все равно перебиваются

2022-11-28 13:16 UTC, sokol-rc commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +  const userRows = userScore.map((user, index) => {
А сейчас это никак не сказывается на производительности, верно?
Часто пишут, не пытайтесь оптимизировать код сразу, пока не настало проблем.

Думаю это можно решить в рамках задачи будущих спринтов, когда будет решаться вопрос перформанса.

Это критичное замечание, или из разряда можно лучше?
Спасибо

2022-11-28 14:17 UTC, lmm1ng approved these changes
Всё ок!

2022-11-28 14:17 UTC, lmm1ng commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +    {
что-то с выравниванием

2022-11-29 10:34 UTC, EzhikTT approved these changes
Все ок

2022-11-29 11:12 UTC, merged