Task 105 input validation zod
5dev-team/BattleCity pull request #52
Opened 2023-02-17 21:22 UTC by Underwindow

Добавить сообщения об ошибках пользовательского ввода

![image](https://user-images.githubusercontent.com/35759068/219796024-9382a6da-f382-4c43-8c18-df84c838c349.png)

2023-02-20 13:53 UTC, EzhikTT requested changes

2023-02-20 13:53 UTC, EzhikTT commented on packages/client/src/components/UI/nes-input/nes-input.tsx
> +          className={`${styles['nes-input__label']} ${labelHidden ? 'visually-hidden' : ''}`}
А новое значение не надо проверять на существование?

2023-02-20 21:47 UTC, Underwindow commented on packages/client/src/components/UI/nes-input/nes-input.tsx
> +          className={`${styles['nes-input__label']} ${labelHidden ? 'visually-hidden' : ''}`}
> А новое значение не надо проверять на существование?
Можете пожалуйста пояснить поподробнее о проверке какого значения вы говорите?

2023-02-21 11:34 UTC, EzhikTT commented on packages/client/src/components/UI/nes-input/nes-input.tsx
> +          className={`${styles['nes-input__label']} ${labelHidden ? 'visually-hidden' : ''}`}
`styles['nes-input__label']` - оно всегда есть? Не может вместо него оказаться `undefined`?

2023-02-21 13:29 UTC, Underwindow commented on packages/client/src/components/UI/nes-input/nes-input.tsx
> +          className={`${styles['nes-input__label']} ${labelHidden ? 'visually-hidden' : ''}`}
> `styles['nes-input__label']` - оно всегда есть? Не может вместо него оказаться `undefined`?

Оно может оказаться undefined в том случае если стили не подгрузятся, но критично ли это? 
Наш проект использует модульный scss и почти в каждом компоненте стили прокидываются таким же образом, есть ли смысл проверять все эти значения на undefined?

2023-02-21 19:34 UTC, merged