Task 106 add change stages
5dev-team/BattleCity pull request #53
Opened 2023-02-17 23:40 UTC by sokol-rc

### Какую задачу решаем
1. Добавлен новый уровень в игру
2. Добавлена возможность смены уровней

2023-02-18 20:46 UTC, Underwindow approved these changes

2023-02-18 20:46 UTC, Underwindow commented on packages/client/src/pages/game/game.tsx
> +  }
Почему решил использовать здесь Promise? Какую ошибку здесь можно получить?
Может лучше реализовать это например таким образом:
![image](https://user-images.githubusercontent.com/35759068/219898812-02f295f0-c9ed-40a1-83d6-9f2a0507d258.png)

2023-02-20 13:55 UTC, EzhikTT requested changes

2023-02-20 13:55 UTC, EzhikTT commented on packages/client/src/pages/game/game.tsx
> +  }
+1. Зачем тут промис?

2023-02-21 17:56 UTC, sokol-rc commented on packages/client/src/pages/game/game.tsx
> +  }
Промис убрал. Его тут действительно не должно быть.
Вынужден слить ветку в dev, т.к. завтра демо.
Остальные правки касаются улучшения игры и не по тз практикума.

2023-02-21 17:56 UTC, sokol-rc commented on packages/client/src/pages/game/game.tsx
> +  }
Прошу понять и простить

2023-02-21 17:57 UTC, merged