feat: add csp
5dev-team/BattleCity pull request #56
Opened 2023-02-18 23:12 UTC by thechertan

### Какую задачу решаем
Добавить CSP в проект

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-02-19 14:09 UTC, sokol-rc commented on packages/server/package.json
> +    "helmet": "^6.0.1",
крышка

2023-02-20 13:59 UTC, EzhikTT requested changes

2023-02-20 13:59 UTC, EzhikTT commented on packages/server/index.ts
> +import * as helmet from 'helmet'
А зачем тут объединять все в один объект? Нельзя вытянуть только нужное?

2023-02-20 14:02 UTC, tsforge commented on packages/server/index.ts
> +import * as helmet from 'helmet'
> А зачем тут объединять все в один объект? Нельзя вытянуть только нужное?

в документации так рекомендуют!
![image](https://user-images.githubusercontent.com/84693047/220128172-ede5fd38-c136-44c9-8ee1-9897a8e3c457.png)

2023-02-20 14:16 UTC, thechertan commented on packages/server/index.ts
> +import * as helmet from 'helmet'
https://github.com/helmetjs/helmet

2023-02-20 18:38 UTC, sokol-rc approved these changes
всё ок

2023-02-21 11:36 UTC, EzhikTT commented on packages/server/index.ts
> +import * as helmet from 'helmet'
Ну ладно) Но это скорее пример, чем рекомендация. У вас можно было бы взять только две функции и все

2023-02-21 11:36 UTC, EzhikTT approved these changes
Все ок

2023-02-22 12:05 UTC, merged