feat(error-boundary): добавлен компонент обработки ошибок
5dev-team/BattleCity pull request #7
Opened 2022-12-02 16:02 UTC by Underwindow

Обработка ошибок react-компонентов

- новый компонент "error-boundary"

2022-12-03 10:55 UTC, EzhikTT commented on packages/client/src/components/error-boundary/error-boundary.tsx
> +  error: Error | null
Мб лучше сделать их опциональными? `error?: Error`

2022-12-03 10:56 UTC, EzhikTT requested changes

2022-12-03 10:56 UTC, EzhikTT commented on packages/client/src/components/error-boundary/error-boundary.tsx
> +class ErrorBoundary extends Component<ErrorBoundaryProps, State> {
Почему здесь классовый компонент?

2022-12-03 12:23 UTC, Underwindow commented on packages/client/src/components/error-boundary/error-boundary.tsx
> +class ErrorBoundary extends Component<ErrorBoundaryProps, State> {
Взял из документации https://ru.reactjs.org/docs/error-boundaries.html#introducing-error-boundaries и в целом в интернете пишут, что на данный момент в реакте нет офиц.хуков которые бы позволили сделать данный компонент функциональным. Есть конечно сторонние библиотеки которые реализуют такие хуки, но я предпочел следовать официальной документации по ErrorBoundary.

2022-12-03 12:36 UTC, Underwindow commented on packages/client/src/components/error-boundary/error-boundary.tsx
> +  error: Error | null
Не знаю, чем это будет лучше? Я думаю, что разницы особо нет undefined или null, но когда я читаю чужой код, то `undefined` и `?:` на первый взгляд кажется чем-то необязательным/неопределенным и чаще воспринимается как плохой тон, но когда пишут null, то сразу акцентируешь на этом внимание, лучше вникаешь в код. 
Плюс мне явно хотелось определить свойство error, когда речь идет о компоненте который работает с ошибками.

2022-12-03 15:04 UTC, sokol-rc commented on packages/client/src/components/error-boundary/error-boundary.tsx
> +class ErrorBoundary extends Component<ErrorBoundaryProps, State> {
Документация подсказывает использовать классовый компонент на всё приложение 
![изображение](https://user-images.githubusercontent.com/83005607/205447463-c4f51807-24fa-4d88-a60d-b1356f9a3041.png)

2022-12-06 15:35 UTC, EzhikTT commented on packages/client/src/components/error-boundary/error-boundary.tsx
> +  error: Error | null
Это зависит от проверки далее. Если проверяете просто приведением типа, то опциональность выглядит логичней. Если вы ожидаете значение всегда и проверяете его null/не_null, то тогда ваш вариант

2022-12-06 15:38 UTC, EzhikTT commented on packages/client/src/components/error-boundary/error-boundary.tsx
> +class ErrorBoundary extends Component<ErrorBoundaryProps, State> {
Да, хорошо)

2022-12-06 15:39 UTC, EzhikTT approved these changes

2022-12-08 19:45 UTC, thechertan commented
все чётко!

2022-12-09 17:14 UTC, merged