feat(game-start-screen): добавлена страница начала игры
5dev-team/BattleCity pull request #9
Opened 2022-12-02 21:53 UTC by Underwindow

Экран начала игры

![image](https://user-images.githubusercontent.com/35759068/205396192-4d141b6d-33b7-4075-a939-b782a96869f1.png)

- добавлена страница начала игры /game
- добавлен новый компонент кнопки bc-button
- добавлено переключение кнопок стрелками вверх/вниз

2022-12-03 10:57 UTC, EzhikTT commented on packages/client/src/App.tsx
>          <Route path='/sign-in' element={<SignIn />} />
Можно пути вынести в константы

2022-12-03 10:58 UTC, EzhikTT requested changes

2022-12-03 10:58 UTC, EzhikTT commented on packages/client/src/components/UI/bc-button/bc-button.tsx
> +  const tryChangeFocus = (element: ChildNode | null | undefined) => {
А в чем `try`, если нет ошибки никакой?

2022-12-03 12:13 UTC, Underwindow commented on packages/client/src/components/UI/bc-button/bc-button.tsx
> +  const tryChangeFocus = (element: ChildNode | null | undefined) => {
в том что не факт что element-ом, будет такая же кнопка, пользователь компонента может сверстать страницу иначе, и этот метод просто "попытается" сменить фокус если есть такая же кнопка по соседству

2022-12-03 14:33 UTC, sokol-rc requested changes
Спасибо за работу!
Классная копия начального экрана танков)
Здорово, что подумал о контроллере!

**Перед продолжением надо исправить несколько моментов:**

- при клике куда-либо пропадает изображение танка.

**Также есть пара вопросов:**

- может фокус стрелками замкнуть внутри `<ul>` например. Тогда не придется проверять наличие соседних элементов.

2022-12-03 14:33 UTC, sokol-rc commented on packages/client/src/components/UI/bc-button/bc-button.tsx
> +import tankIcon from '../../../assets/avatarPlaceholder.png'
У нас уже есть alias src "@/", лучше поставить его.

2022-12-03 14:33 UTC, sokol-rc commented on packages/client/src/pages/game/game.tsx
> +          <BCButton>2 PLAYERS</BCButton>
Можно сразу подготовить вызов initGame с параметром для 2-х игроков

2022-12-03 14:33 UTC, sokol-rc commented on packages/client/src/pages/game/game.tsx
> +          className={`${styles['logo']}`}
Лучше указание класса привести к одному формату

2022-12-03 14:33 UTC, sokol-rc commented on packages/client/src/pages/game/game.tsx
> +import logo from '../../assets/battleCityLogo.png'
У нас уже есть alias src "@/", лучше поставить его.

2022-12-03 14:33 UTC, sokol-rc commented on packages/client/src/pages/game/game.module.scss
> +  height: 20vh;
А почему высота относительно высоты браузера? Логотип деформируется в зависимости от окна

2022-12-03 14:33 UTC, sokol-rc commented on packages/client/src/components/UI/bc-button/bc-button.tsx
> +        <img className={`${styles['bc-btn__icon']}`} src={icon || tankIcon} />
Не хватает атрибута alt

2022-12-03 14:33 UTC, sokol-rc commented on packages/client/src/components/UI/bc-button/bc-button.tsx
> +  const [isFocused, setFocus] = useState(focus ? true : false)
Можно упросить до `!!focus`

2022-12-03 14:57 UTC, sokol-rc commented on packages/client/src/components/UI/bc-button/bc-button.tsx
> +    node?.addEventListener('keydown', listener, {
Лучше удалять EventLisneter перед ререндером

2022-12-05 00:48 UTC, sokol-rc approved these changes
Всё круто)

2022-12-05 00:48 UTC, sokol-rc commented on packages/client/src/pages/game/game.tsx
> +          <GameButton onClick={() => initGame(2)}>2 PLAYERS</GameButton>
Лучше явно указать
initGame(1)
initGame(2)

Так лучше читается, а то значение по-умолчанию надо возвращаться и смотреть

2022-12-05 16:52 UTC, merged

2022-12-06 15:32 UTC, EzhikTT commented
Все окей)